# Makefile for building the parser

CC=gcc
CFLAGS=-O2 -Wall -ansi -pedantic -g
RM=rm -f

TARGET = parser
OBJS = error.o alloc.o main.o
ALLFILES = $(OBJS) $(TARGET)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) -o $@ $?

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean

clean:
	$(RM) $(ALLFILES)

# automatically generated by `gcc -MM *.c`
# DO NOT DELETE
alloc.o: alloc.c alloc.h error.h
error.o: error.c error.h
main.o: main.c
